name: Build and Upload Artifacts (Dockerized)

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Select OS for Docker Build Environment'
        required: true
        default: '20.04'
        type: choice
        options:
          - 20.04
          - 22.04
          - 24.04
          - latest

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Set environment variables
        run: |
          echo "DEPLOYMENT=${{ github.workspace }}/build" >> "$GITHUB_ENV"
          echo "DOCKER_DEPLOYMENT=/app/build" >> "$GITHUB_ENV"
          echo "GOOS=linux" >> "$GITHUB_ENV"
          echo "GOARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"

      - name: Build the project (in Docker)
        shell: bash
        run: |
          if [[ "$GOARCH" == "amd64" ]]; then
            DEST="${{ env.DEPLOYMENT }}/linux64"
            DOCKER_DEST="${{ env.DOCKER_DEPLOYMENT }}/linux64"
          elif [[ "$GOARCH" == "arm64" ]]; then
            DEST="${{ env.DEPLOYMENT }}/linux-arm64"
            DOCKER_DEST="${{ env.DOCKER_DEPLOYMENT }}/linux-arm64"
          fi

          mkdir -p "$DEST"

          cat << 'EOF' > .github/docker_build_internal.sh
          set -e
          apt-get update && apt-get install -y wget curl gnupg ca-certificates
          wget -q https://go.dev/dl/go1.25.0.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.25.0.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin

          go version
          echo "Building for $GOOS/$GOARCH to $DEST"

          go build -C /app/cmd -v -o "$DEST/ts-dns" -trimpath -ldflags "-w -s" .
          EOF

          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app/cmd \
            -e GOOS=$GOOS \
            -e GOARCH=$GOARCH \
            -e DEST="$DOCKER_DEST" \
            ubuntu:${{ github.event.inputs.os }} \
            /bin/bash /app/.github/docker_build_internal.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.inputs.os }}-${{ matrix.arch }}
          path: ${{ env.DEPLOYMENT }}
